import { pool } from './client.js';
import dotenv from 'dotenv';
dotenv.config();

// Helper to build minimal starter code for a function name
function js(fn: string, args: string, ret: string) {
  return `function ${fn}(${args}) {\n\n}\n\nconst input = JSON.parse(require('fs').readFileSync('/dev/stdin','utf8').trim());\nconsole.log(JSON.stringify(${fn}(...(Array.isArray(input[0]) ? input : [input]))));\n`;
}
function py(fn: string, args: string) {
  return `def ${fn}(${args}):\n    pass\n\nimport sys, json\ndata = json.loads(sys.stdin.readline())\nprint(json.dumps(${fn}(*data) if isinstance(data, list) else ${fn}(data)))\n`;
}

const problems = [
  // ── EASY (20) ─────────────────────────────────────────────────────────────
  {
    slug: 'reverse-string',
    title: 'Reverse a String',
    difficulty: 'easy',
    description: 'Given a string `s`, return it reversed without using built-in reverse methods.',
    examples: [{ input: 's = "hello"', output: '"olleh"' }, { input: 's = "abcd"', output: '"dcba"' }],
    constraints: ['1 <= s.length <= 10^5', 's contains only printable ASCII characters'],
    tags: ['strings'],
    starterCode: { 93: js('reverseString','s','string'), 71: py('reverse_string','s') },
    testCases: [{ input: '"hello"', expectedOutput: '"olleh"' }, { input: '"abcd"', expectedOutput: '"dcba"' }],
    acceptanceRate: 82.1,
  },
  {
    slug: 'palindrome-check',
    title: 'Palindrome Check',
    difficulty: 'easy',
    description: 'Return `true` if the string `s` reads the same forwards and backwards (ignore case, alphanumeric only).',
    examples: [{ input: 's = "racecar"', output: 'true' }, { input: 's = "hello"', output: 'false' }],
    constraints: ['1 <= s.length <= 2*10^5'],
    tags: ['strings'],
    starterCode: { 93: js('isPalindrome','s','boolean'), 71: py('is_palindrome','s') },
    testCases: [{ input: '"racecar"', expectedOutput: 'true' }, { input: '"hello"', expectedOutput: 'false' }, { input: '"A man a plan a canal Panama"', expectedOutput: 'true' }],
    acceptanceRate: 78.3,
  },
  {
    slug: 'count-vowels',
    title: 'Count Vowels',
    difficulty: 'easy',
    description: 'Count the number of vowels (a, e, i, o, u — both cases) in string `s`.',
    examples: [{ input: 's = "Hello World"', output: '3' }],
    constraints: ['1 <= s.length <= 10^5'],
    tags: ['strings'],
    starterCode: { 93: js('countVowels','s','number'), 71: py('count_vowels','s') },
    testCases: [{ input: '"Hello World"', expectedOutput: '3' }, { input: '"aeiou"', expectedOutput: '5' }, { input: '"xyz"', expectedOutput: '0' }],
    acceptanceRate: 88.0,
  },
  {
    slug: 'find-max-in-array',
    title: 'Find Maximum in Array',
    difficulty: 'easy',
    description: 'Given an integer array `nums`, return the maximum element.',
    examples: [{ input: 'nums = [3,1,4,1,5,9]', output: '9' }],
    constraints: ['1 <= nums.length <= 10^5', '-10^9 <= nums[i] <= 10^9'],
    tags: ['arrays'],
    starterCode: { 93: js('findMax','nums','number'), 71: py('find_max','nums') },
    testCases: [{ input: '[[3,1,4,1,5,9]]', expectedOutput: '9' }, { input: '[[-1,-5,-2]]', expectedOutput: '-1' }],
    acceptanceRate: 91.2,
  },
  {
    slug: 'fizzbuzz',
    title: 'FizzBuzz',
    difficulty: 'easy',
    description: 'Return an array of strings for 1 to `n`. Use "Fizz" for multiples of 3, "Buzz" for 5, "FizzBuzz" for both.',
    examples: [{ input: 'n = 5', output: '["1","2","Fizz","4","Buzz"]' }],
    constraints: ['1 <= n <= 10^4'],
    tags: ['arrays', 'strings'],
    starterCode: { 93: js('fizzBuzz','n','string[]'), 71: py('fizz_buzz','n') },
    testCases: [{ input: '[5]', expectedOutput: '["1","2","Fizz","4","Buzz"]' }, { input: '[15]', expectedOutput: '["1","2","Fizz","4","Buzz","Fizz","7","8","Fizz","Buzz","11","Fizz","13","14","FizzBuzz"]' }],
    acceptanceRate: 90.5,
  },
  {
    slug: 'sum-of-digits',
    title: 'Sum of Digits',
    difficulty: 'easy',
    description: 'Given a non-negative integer `n`, return the sum of its digits.',
    examples: [{ input: 'n = 1234', output: '10' }],
    constraints: ['0 <= n <= 10^9'],
    tags: ['math'],
    starterCode: { 93: js('sumDigits','n','number'), 71: py('sum_digits','n') },
    testCases: [{ input: '[1234]', expectedOutput: '10' }, { input: '[0]', expectedOutput: '0' }, { input: '[999]', expectedOutput: '27' }],
    acceptanceRate: 87.4,
  },
  {
    slug: 'remove-duplicates-sorted',
    title: 'Remove Duplicates from Sorted Array',
    difficulty: 'easy',
    description: 'Given a sorted array `nums`, remove duplicates in-place and return the count of unique elements.',
    examples: [{ input: 'nums = [1,1,2,3,3]', output: '3' }],
    constraints: ['1 <= nums.length <= 3*10^4', 'nums is sorted ascending'],
    tags: ['arrays', 'two-pointers'],
    starterCode: { 93: js('removeDuplicates','nums','number'), 71: py('remove_duplicates','nums') },
    testCases: [{ input: '[[1,1,2,3,3]]', expectedOutput: '3' }, { input: '[[1,2,3]]', expectedOutput: '3' }],
    acceptanceRate: 74.8,
  },
  {
    slug: 'valid-parentheses',
    title: 'Valid Parentheses',
    difficulty: 'easy',
    description: 'Given a string `s` with `(`, `)`, `{`, `}`, `[`, `]`, determine if it is valid (every open bracket closed in order).',
    examples: [{ input: 's = "()[]{}"', output: 'true' }, { input: 's = "(]"', output: 'false' }],
    constraints: ['1 <= s.length <= 10^4', 's consists of brackets only'],
    tags: ['stack', 'strings'],
    starterCode: { 93: js('isValid','s','boolean'), 71: py('is_valid','s') },
    testCases: [{ input: '"()[]{}"', expectedOutput: 'true' }, { input: '"(]"', expectedOutput: 'false' }, { input: '"([)]"', expectedOutput: 'false' }],
    acceptanceRate: 71.2,
  },
  {
    slug: 'missing-number',
    title: 'Missing Number',
    difficulty: 'easy',
    description: 'Given an array of `n` distinct numbers from `0` to `n`, find the one missing number.',
    examples: [{ input: 'nums = [3,0,1]', output: '2' }],
    constraints: ['n == nums.length', '1 <= n <= 10^4', 'All numbers are distinct'],
    tags: ['arrays', 'math'],
    starterCode: { 93: js('missingNumber','nums','number'), 71: py('missing_number','nums') },
    testCases: [{ input: '[[3,0,1]]', expectedOutput: '2' }, { input: '[[0,1]]', expectedOutput: '2' }, { input: '[[9,6,4,2,3,5,7,0,1]]', expectedOutput: '8' }],
    acceptanceRate: 68.9,
  },
  {
    slug: 'first-unique-char',
    title: 'First Unique Character',
    difficulty: 'easy',
    description: 'Given a string `s`, return the index of the first non-repeating character. Return -1 if none exists.',
    examples: [{ input: 's = "leetcode"', output: '0' }, { input: 's = "aabb"', output: '-1' }],
    constraints: ['1 <= s.length <= 10^5', 's consists of lowercase English letters'],
    tags: ['strings', 'hash-map'],
    starterCode: { 93: js('firstUniqChar','s','number'), 71: py('first_uniq_char','s') },
    testCases: [{ input: '"leetcode"', expectedOutput: '0' }, { input: '"aabb"', expectedOutput: '-1' }, { input: '"loveleet"', expectedOutput: '2' }],
    acceptanceRate: 62.7,
  },
  {
    slug: 'power-of-two',
    title: 'Power of Two',
    difficulty: 'easy',
    description: 'Given an integer `n`, return `true` if it is a power of two.',
    examples: [{ input: 'n = 16', output: 'true' }, { input: 'n = 3', output: 'false' }],
    constraints: ['-2^31 <= n <= 2^31 - 1'],
    tags: ['math', 'bit-manipulation'],
    starterCode: { 93: js('isPowerOfTwo','n','boolean'), 71: py('is_power_of_two','n') },
    testCases: [{ input: '[16]', expectedOutput: 'true' }, { input: '[3]', expectedOutput: 'false' }, { input: '[1]', expectedOutput: 'true' }],
    acceptanceRate: 69.4,
  },
  {
    slug: 'contains-duplicate',
    title: 'Contains Duplicate',
    difficulty: 'easy',
    description: 'Return `true` if any value in `nums` appears at least twice.',
    examples: [{ input: 'nums = [1,2,3,1]', output: 'true' }],
    constraints: ['1 <= nums.length <= 10^5', '-10^9 <= nums[i] <= 10^9'],
    tags: ['arrays', 'hash-map'],
    starterCode: { 93: js('containsDuplicate','nums','boolean'), 71: py('contains_duplicate','nums') },
    testCases: [{ input: '[[1,2,3,1]]', expectedOutput: 'true' }, { input: '[[1,2,3,4]]', expectedOutput: 'false' }],
    acceptanceRate: 80.1,
  },
  {
    slug: 'merge-sorted-arrays',
    title: 'Merge Two Sorted Arrays',
    difficulty: 'easy',
    description: 'Merge two sorted integer arrays `a` and `b` into one sorted array.',
    examples: [{ input: 'a=[1,3,5], b=[2,4,6]', output: '[1,2,3,4,5,6]' }],
    constraints: ['0 <= a.length, b.length <= 10^4', 'Both arrays are sorted'],
    tags: ['arrays', 'sorting'],
    starterCode: { 93: js('mergeSorted','a, b','number[]'), 71: py('merge_sorted','a, b') },
    testCases: [{ input: '[[1,3,5],[2,4,6]]', expectedOutput: '[1,2,3,4,5,6]' }, { input: '[[],[1,2]]', expectedOutput: '[1,2]' }],
    acceptanceRate: 76.5,
  },
  {
    slug: 'single-number',
    title: 'Single Number',
    difficulty: 'easy',
    description: 'Every element in `nums` appears twice except one. Find that single element using O(1) extra space.',
    examples: [{ input: 'nums = [4,1,2,1,2]', output: '4' }],
    constraints: ['1 <= nums.length <= 3*10^4', 'Each element appears exactly twice except one'],
    tags: ['arrays', 'bit-manipulation'],
    starterCode: { 93: js('singleNumber','nums','number'), 71: py('single_number','nums') },
    testCases: [{ input: '[[4,1,2,1,2]]', expectedOutput: '4' }, { input: '[[2,2,1]]', expectedOutput: '1' }],
    acceptanceRate: 77.3,
  },
  {
    slug: 'roman-to-integer',
    title: 'Roman to Integer',
    difficulty: 'easy',
    description: 'Convert a Roman numeral string `s` to an integer.',
    examples: [{ input: 's = "III"', output: '3' }, { input: 's = "IX"', output: '9' }, { input: 's = "LVIII"', output: '58' }],
    constraints: ['1 <= s.length <= 15', 's contains valid Roman numeral characters'],
    tags: ['strings', 'hash-map'],
    starterCode: { 93: js('romanToInt','s','number'), 71: py('roman_to_int','s') },
    testCases: [{ input: '"III"', expectedOutput: '3' }, { input: '"IX"', expectedOutput: '9' }, { input: '"MCMXCIV"', expectedOutput: '1994' }],
    acceptanceRate: 63.8,
  },
  {
    slug: 'fibonacci-number',
    title: 'Fibonacci Number',
    difficulty: 'easy',
    description: 'Return the `n`th Fibonacci number where F(0)=0, F(1)=1.',
    examples: [{ input: 'n = 6', output: '8' }],
    constraints: ['0 <= n <= 30'],
    tags: ['recursion', 'dynamic-programming'],
    starterCode: { 93: js('fib','n','number'), 71: py('fib','n') },
    testCases: [{ input: '[6]', expectedOutput: '8' }, { input: '[0]', expectedOutput: '0' }, { input: '[10]', expectedOutput: '55' }],
    acceptanceRate: 83.2,
  },
  {
    slug: 'longest-common-prefix',
    title: 'Longest Common Prefix',
    difficulty: 'easy',
    description: 'Find the longest common prefix string among an array of strings `strs`. Return `""` if none.',
    examples: [{ input: 'strs = ["flower","flow","flight"]', output: '"fl"' }],
    constraints: ['1 <= strs.length <= 200', '0 <= strs[i].length <= 200'],
    tags: ['strings'],
    starterCode: { 93: js('longestCommonPrefix','strs','string'), 71: py('longest_common_prefix','strs') },
    testCases: [{ input: '[["flower","flow","flight"]]', expectedOutput: '"fl"' }, { input: '[["dog","racecar","car"]]', expectedOutput: '""' }],
    acceptanceRate: 58.6,
  },
  {
    slug: 'max-subarray-sum',
    title: 'Maximum Subarray Sum',
    difficulty: 'easy',
    description: 'Find the contiguous subarray with the largest sum (Kadane\'s Algorithm).',
    examples: [{ input: 'nums = [-2,1,-3,4,-1,2,1,-5,4]', output: '6' }],
    constraints: ['1 <= nums.length <= 10^5', '-10^4 <= nums[i] <= 10^4'],
    tags: ['arrays', 'dynamic-programming'],
    starterCode: { 93: js('maxSubArray','nums','number'), 71: py('max_sub_array','nums') },
    testCases: [{ input: '[[-2,1,-3,4,-1,2,1,-5,4]]', expectedOutput: '6' }, { input: '[[1]]', expectedOutput: '1' }],
    acceptanceRate: 66.4,
  },
  {
    slug: 'is-anagram',
    title: 'Valid Anagram',
    difficulty: 'easy',
    description: 'Return `true` if `t` is an anagram of `s`.',
    examples: [{ input: 's="anagram", t="nagaram"', output: 'true' }],
    constraints: ['1 <= s.length, t.length <= 5*10^4', 'Both contain lowercase letters'],
    tags: ['strings', 'hash-map', 'sorting'],
    starterCode: { 93: js('isAnagram','s, t','boolean'), 71: py('is_anagram','s, t') },
    testCases: [{ input: '["anagram","nagaram"]', expectedOutput: 'true' }, { input: '["rat","car"]', expectedOutput: 'false' }],
    acceptanceRate: 72.9,
  },
  {
    slug: 'binary-search',
    title: 'Binary Search',
    difficulty: 'easy',
    description: 'Given a sorted array `nums` and a `target`, return its index or -1 if not found.',
    examples: [{ input: 'nums=[-1,0,3,5,9,12], target=9', output: '4' }],
    constraints: ['1 <= nums.length <= 10^4', 'All elements unique, sorted ascending'],
    tags: ['arrays', 'searching', 'binary-search'],
    starterCode: { 93: js('search','nums, target','number'), 71: py('search','nums, target') },
    testCases: [{ input: '[[-1,0,3,5,9,12],9]', expectedOutput: '4' }, { input: '[[-1,0,3,5,9,12],2]', expectedOutput: '-1' }],
    acceptanceRate: 74.5,
  },

  // ── MEDIUM (50) ───────────────────────────────────────────────────────────
  {
    slug: 'two-sum',
    title: 'Two Sum',
    difficulty: 'medium',
    description: 'Given an array of integers `nums` and a `target`, return indices of the two numbers that add up to `target`. Each input has exactly one solution.',
    examples: [{ input: 'nums=[2,7,11,15], target=9', output: '[0,1]' }],
    constraints: ['2 <= nums.length <= 10^4', 'Only one valid answer exists'],
    tags: ['arrays', 'hash-map'],
    starterCode: { 93: js('twoSum','nums, target','number[]'), 71: py('two_sum','nums, target') },
    testCases: [{ input: '[[2,7,11,15],9]', expectedOutput: '[0,1]' }, { input: '[[3,2,4],6]', expectedOutput: '[1,2]' }],
    acceptanceRate: 49.5,
  },
  {
    slug: 'longest-substring-no-repeat',
    title: 'Longest Substring Without Repeating',
    difficulty: 'medium',
    description: 'Find the length of the longest substring without repeating characters.',
    examples: [{ input: 's="abcabcbb"', output: '3' }],
    constraints: ['0 <= s.length <= 5*10^4', 's consists of printable ASCII'],
    tags: ['strings', 'hash-map', 'sliding-window'],
    starterCode: { 93: js('lengthOfLongestSubstring','s','number'), 71: py('length_of_longest_substring','s') },
    testCases: [{ input: '"abcabcbb"', expectedOutput: '3' }, { input: '"bbbbb"', expectedOutput: '1' }, { input: '"pwwkew"', expectedOutput: '3' }],
    acceptanceRate: 44.2,
  },
  {
    slug: 'group-anagrams',
    title: 'Group Anagrams',
    difficulty: 'medium',
    description: 'Group an array of strings `strs` such that anagrams are together. Return groups in any order.',
    examples: [{ input: 'strs=["eat","tea","tan","ate","nat","bat"]', output: '[["bat"],["nat","tan"],["ate","eat","tea"]]' }],
    constraints: ['1 <= strs.length <= 10^4', '0 <= strs[i].length <= 100'],
    tags: ['strings', 'hash-map', 'sorting'],
    starterCode: { 93: js('groupAnagrams','strs','string[][]'), 71: py('group_anagrams','strs') },
    testCases: [{ input: '[["eat","tea","tan","ate","nat","bat"]]', expectedOutput: '[["bat"],["nat","tan"],["ate","eat","tea"]]' }],
    acceptanceRate: 51.3,
  },
  {
    slug: 'product-except-self',
    title: 'Product of Array Except Self',
    difficulty: 'medium',
    description: 'Return array where `output[i]` is product of all elements except `nums[i]`. No division, O(n) time.',
    examples: [{ input: 'nums=[1,2,3,4]', output: '[24,12,8,6]' }],
    constraints: ['2 <= nums.length <= 10^5', 'Output fits 32-bit integer'],
    tags: ['arrays'],
    starterCode: { 93: js('productExceptSelf','nums','number[]'), 71: py('product_except_self','nums') },
    testCases: [{ input: '[[1,2,3,4]]', expectedOutput: '[24,12,8,6]' }, { input: '[[-1,1,0,-3,3]]', expectedOutput: '[0,0,9,0,0]' }],
    acceptanceRate: 40.1,
  },
  {
    slug: 'top-k-frequent',
    title: 'Top K Frequent Elements',
    difficulty: 'medium',
    description: 'Return the `k` most frequent elements in `nums`. Answer in any order.',
    examples: [{ input: 'nums=[1,1,1,2,2,3], k=2', output: '[1,2]' }],
    constraints: ['1 <= nums.length <= 10^5', 'k is valid', 'Answer is unique'],
    tags: ['arrays', 'hash-map', 'heap', 'sorting'],
    starterCode: { 93: js('topKFrequent','nums, k','number[]'), 71: py('top_k_frequent','nums, k') },
    testCases: [{ input: '[[1,1,1,2,2,3],2]', expectedOutput: '[1,2]' }, { input: '[[1],1]', expectedOutput: '[1]' }],
    acceptanceRate: 48.7,
  },
  {
    slug: 'encode-decode-strings',
    title: 'Encode and Decode Strings',
    difficulty: 'medium',
    description: 'Design an algorithm to encode a list of strings into a single string and decode it back.',
    examples: [{ input: '["hello","world"]', output: '"hello","world"' }],
    constraints: ['0 <= strs.length <= 200', '0 <= strs[i].length <= 200'],
    tags: ['strings', 'serialization'],
    starterCode: { 93: '// implement encode(strs) and decode(str)\nfunction encode(strs) {\n\n}\nfunction decode(str) {\n\n}', 71: 'def encode(strs):\n    pass\ndef decode(s):\n    pass' },
    testCases: [{ input: '[["hello","world"]]', expectedOutput: '["hello","world"]' }],
    acceptanceRate: 39.6,
  },
  {
    slug: 'valid-sudoku',
    title: 'Valid Sudoku',
    difficulty: 'medium',
    description: 'Determine if a 9x9 Sudoku board is valid (each row, column, 3x3 box has no duplicates).',
    examples: [{ input: 'board (9x9 2D array)', output: 'true or false' }],
    constraints: ['Board is 9x9', 'Cells contain "1"-"9" or "."'],
    tags: ['arrays', 'hash-map'],
    starterCode: { 93: js('isValidSudoku','board','boolean'), 71: py('is_valid_sudoku','board') },
    testCases: [{ input: '[["5","3",".",".","7",".",".",".","."],["6",".",".","1","9","5",".",".","."],[".","9","8",".",".",".",".","6","."],["8",".",".",".","6",".",".",".","3"],["4",".",".","8",".","3",".",".","1"],["7",".",".",".","2",".",".",".","6"],[".","6",".",".",".",".","2","8","."],[".",".",".","4","1","9",".",".","5"],[".",".",".",".","8",".",".","7","9"]]', expectedOutput: 'true' }],
    acceptanceRate: 36.2,
  },
  {
    slug: 'max-profit-stocks',
    title: 'Best Time to Buy and Sell Stock',
    difficulty: 'medium',
    description: 'Find max profit from one buy-sell transaction. You must buy before you sell.',
    examples: [{ input: 'prices=[7,1,5,3,6,4]', output: '5' }],
    constraints: ['1 <= prices.length <= 10^5', '0 <= prices[i] <= 10^4'],
    tags: ['arrays', 'dynamic-programming'],
    starterCode: { 93: js('maxProfit','prices','number'), 71: py('max_profit','prices') },
    testCases: [{ input: '[[7,1,5,3,6,4]]', expectedOutput: '5' }, { input: '[[7,6,4,3,1]]', expectedOutput: '0' }],
    acceptanceRate: 54.6,
  },
  {
    slug: 'coin-change',
    title: 'Coin Change',
    difficulty: 'medium',
    description: 'Given coin denominations `coins` and an amount `amount`, return min coins needed. Return -1 if impossible.',
    examples: [{ input: 'coins=[1,5,10], amount=11', output: '2' }],
    constraints: ['1 <= coins.length <= 12', '0 <= amount <= 10^4'],
    tags: ['dynamic-programming'],
    starterCode: { 93: js('coinChange','coins, amount','number'), 71: py('coin_change','coins, amount') },
    testCases: [{ input: '[[1,5,10],11]', expectedOutput: '2' }, { input: '[[2],3]', expectedOutput: '-1' }],
    acceptanceRate: 33.8,
  },
  {
    slug: 'climbing-stairs',
    title: 'Climbing Stairs',
    difficulty: 'medium',
    description: 'You can climb 1 or 2 steps at a time. How many distinct ways to reach step `n`?',
    examples: [{ input: 'n=3', output: '3' }],
    constraints: ['1 <= n <= 45'],
    tags: ['dynamic-programming', 'recursion'],
    starterCode: { 93: js('climbStairs','n','number'), 71: py('climb_stairs','n') },
    testCases: [{ input: '[3]', expectedOutput: '3' }, { input: '[5]', expectedOutput: '8' }],
    acceptanceRate: 58.2,
  },
  {
    slug: 'house-robber',
    title: 'House Robber',
    difficulty: 'medium',
    description: 'Max money you can rob from houses in a row without robbing adjacent houses.',
    examples: [{ input: 'nums=[2,7,9,3,1]', output: '12' }],
    constraints: ['1 <= nums.length <= 100', '0 <= nums[i] <= 400'],
    tags: ['dynamic-programming', 'arrays'],
    starterCode: { 93: js('rob','nums','number'), 71: py('rob','nums') },
    testCases: [{ input: '[[2,7,9,3,1]]', expectedOutput: '12' }, { input: '[[1,2,3,1]]', expectedOutput: '4' }],
    acceptanceRate: 47.1,
  },
  {
    slug: 'unique-paths',
    title: 'Unique Paths',
    difficulty: 'medium',
    description: 'Count paths from top-left to bottom-right of an `m x n` grid. You can only move right or down.',
    examples: [{ input: 'm=3, n=7', output: '28' }],
    constraints: ['1 <= m, n <= 100'],
    tags: ['dynamic-programming', 'math'],
    starterCode: { 93: js('uniquePaths','m, n','number'), 71: py('unique_paths','m, n') },
    testCases: [{ input: '[3,7]', expectedOutput: '28' }, { input: '[3,2]', expectedOutput: '3' }],
    acceptanceRate: 52.4,
  },
  {
    slug: 'word-search',
    title: 'Word Search in Grid',
    difficulty: 'medium',
    description: 'Given a 2D board and a word, return true if the word exists in the grid (adjacent horizontally/vertically).',
    examples: [{ input: 'board=[["A","B"],["C","D"]], word="AB"', output: 'true' }],
    constraints: ['1 <= m, n <= 6', '1 <= word.length <= 15'],
    tags: ['graphs', 'dfs', 'recursion', 'backtracking'],
    starterCode: { 93: js('exist','board, word','boolean'), 71: py('exist','board, word') },
    testCases: [{ input: '[[["A","B","C","E"],["S","F","C","S"],["A","D","E","E"]],"ABCCED"]', expectedOutput: 'true' }, { input: '[[["A","B","C","E"],["S","F","C","S"],["A","D","E","E"]],"ABCB"]', expectedOutput: 'false' }],
    acceptanceRate: 35.1,
  },
  {
    slug: 'number-of-islands',
    title: 'Number of Islands',
    difficulty: 'medium',
    description: 'Count the number of islands in a 2D binary grid (1=land, 0=water). Islands are connected land cells.',
    examples: [{ input: 'grid has 3 islands', output: '3' }],
    constraints: ['1 <= m, n <= 300', 'grid[i][j] is "0" or "1"'],
    tags: ['graphs', 'bfs', 'dfs'],
    starterCode: { 93: js('numIslands','grid','number'), 71: py('num_islands','grid') },
    testCases: [{ input: '[[["1","1","0","0","0"],["1","1","0","0","0"],["0","0","1","0","0"],["0","0","0","1","1"]]]', expectedOutput: '3' }],
    acceptanceRate: 41.7,
  },
  {
    slug: 'lru-cache',
    title: 'LRU Cache',
    difficulty: 'medium',
    description: 'Design an LRU cache with `get(key)` and `put(key, value)` in O(1). Evict least recently used when full.',
    examples: [{ input: 'capacity=2, ops=[put(1,1),put(2,2),get(1),put(3,3),get(2)]', output: '[null,null,1,null,-1]' }],
    constraints: ['1 <= capacity <= 3000', '0 <= key, value <= 10^4'],
    tags: ['hash-map', 'linked-list', 'oop'],
    starterCode: { 93: '// Design LRU Cache class\nclass LRUCache {\n  constructor(capacity) {}\n  get(key) {}\n  put(key, value) {}\n}', 71: 'class LRUCache:\n    def __init__(self, capacity): pass\n    def get(self, key): pass\n    def put(self, key, value): pass' },
    testCases: [{ input: '[2,[[1,1],[2,2],[1],[3,3],[2]]]', expectedOutput: '[null,null,1,null,-1]' }],
    acceptanceRate: 30.5,
  },
  {
    slug: 'kth-largest-element',
    title: 'Kth Largest Element',
    difficulty: 'medium',
    description: 'Find the `k`th largest element in an unsorted array (not kth distinct).',
    examples: [{ input: 'nums=[3,2,1,5,6,4], k=2', output: '5' }],
    constraints: ['1 <= k <= nums.length <= 10^4'],
    tags: ['arrays', 'heap', 'sorting'],
    starterCode: { 93: js('findKthLargest','nums, k','number'), 71: py('find_kth_largest','nums, k') },
    testCases: [{ input: '[[3,2,1,5,6,4],2]', expectedOutput: '5' }, { input: '[[3,2,3,1,2,4,5,5,6],4]', expectedOutput: '4' }],
    acceptanceRate: 44.3,
  },
  {
    slug: 'rotate-image',
    title: 'Rotate Image',
    difficulty: 'medium',
    description: 'Rotate an n×n matrix 90° clockwise in-place.',
    examples: [{ input: 'matrix=[[1,2,3],[4,5,6],[7,8,9]]', output: '[[7,4,1],[8,5,2],[9,6,3]]' }],
    constraints: ['n == matrix.length == matrix[i].length', '1 <= n <= 20'],
    tags: ['arrays', 'math'],
    starterCode: { 93: js('rotate','matrix','void'), 71: py('rotate','matrix') },
    testCases: [{ input: '[[[1,2,3],[4,5,6],[7,8,9]]]', expectedOutput: '[[7,4,1],[8,5,2],[9,6,3]]' }],
    acceptanceRate: 45.8,
  },
  {
    slug: 'spiral-matrix',
    title: 'Spiral Matrix',
    difficulty: 'medium',
    description: 'Return all elements of an m×n matrix in spiral order.',
    examples: [{ input: 'matrix=[[1,2,3],[4,5,6],[7,8,9]]', output: '[1,2,3,6,9,8,7,4,5]' }],
    constraints: ['m == matrix.length', 'n == matrix[i].length', '1 <= m, n <= 10'],
    tags: ['arrays'],
    starterCode: { 93: js('spiralOrder','matrix','number[]'), 71: py('spiral_order','matrix') },
    testCases: [{ input: '[[[1,2,3],[4,5,6],[7,8,9]]]', expectedOutput: '[1,2,3,6,9,8,7,4,5]' }],
    acceptanceRate: 37.9,
  },
  {
    slug: 'jump-game',
    title: 'Jump Game',
    difficulty: 'medium',
    description: 'Given `nums[i]` is max jump from index `i`, return whether you can reach the last index.',
    examples: [{ input: 'nums=[2,3,1,1,4]', output: 'true' }],
    constraints: ['1 <= nums.length <= 3*10^4', '0 <= nums[i] <= 10^5'],
    tags: ['arrays', 'dynamic-programming', 'greedy'],
    starterCode: { 93: js('canJump','nums','boolean'), 71: py('can_jump','nums') },
    testCases: [{ input: '[[2,3,1,1,4]]', expectedOutput: 'true' }, { input: '[[3,2,1,0,4]]', expectedOutput: 'false' }],
    acceptanceRate: 42.6,
  },
  {
    slug: 'meeting-rooms-ii',
    title: 'Meeting Rooms II',
    difficulty: 'medium',
    description: 'Find minimum number of conference rooms for given intervals `[[start,end],...]`.',
    examples: [{ input: 'intervals=[[0,30],[5,10],[15,20]]', output: '2' }],
    constraints: ['0 <= intervals.length <= 10^4'],
    tags: ['arrays', 'heap', 'sorting', 'greedy'],
    starterCode: { 93: js('minMeetingRooms','intervals','number'), 71: py('min_meeting_rooms','intervals') },
    testCases: [{ input: '[[[0,30],[5,10],[15,20]]]', expectedOutput: '2' }, { input: '[[[7,10],[2,4]]]', expectedOutput: '1' }],
    acceptanceRate: 38.7,
  },
  {
    slug: 'subsets',
    title: 'Subsets',
    difficulty: 'medium',
    description: 'Return all possible subsets (power set) of `nums`. No duplicates.',
    examples: [{ input: 'nums=[1,2,3]', output: '[[],[1],[2],[1,2],[3],[1,3],[2,3],[1,2,3]]' }],
    constraints: ['1 <= nums.length <= 10', 'All elements unique'],
    tags: ['arrays', 'recursion', 'backtracking'],
    starterCode: { 93: js('subsets','nums','number[][]'), 71: py('subsets','nums') },
    testCases: [{ input: '[[1,2,3]]', expectedOutput: '[[],[1],[2],[1,2],[3],[1,3],[2,3],[1,2,3]]' }],
    acceptanceRate: 55.3,
  },
  {
    slug: 'permutations',
    title: 'Permutations',
    difficulty: 'medium',
    description: 'Return all possible permutations of `nums` (distinct integers).',
    examples: [{ input: 'nums=[1,2,3]', output: '[[1,2,3],[1,3,2],[2,1,3],[2,3,1],[3,1,2],[3,2,1]]' }],
    constraints: ['1 <= nums.length <= 6', 'All distinct'],
    tags: ['arrays', 'recursion', 'backtracking'],
    starterCode: { 93: js('permute','nums','number[][]'), 71: py('permute','nums') },
    testCases: [{ input: '[[1,2,3]]', expectedOutput: '[[1,2,3],[1,3,2],[2,1,3],[2,3,1],[3,1,2],[3,2,1]]' }],
    acceptanceRate: 50.8,
  },
  {
    slug: 'combination-sum',
    title: 'Combination Sum',
    difficulty: 'medium',
    description: 'Find all unique combinations of `candidates` that sum to `target`. Numbers may reuse.',
    examples: [{ input: 'candidates=[2,3,6,7], target=7', output: '[[2,2,3],[7]]' }],
    constraints: ['1 <= candidates.length <= 30', '2 <= candidates[i] <= 40', 'All distinct'],
    tags: ['arrays', 'recursion', 'backtracking'],
    starterCode: { 93: js('combinationSum','candidates, target','number[][]'), 71: py('combination_sum','candidates, target') },
    testCases: [{ input: '[[2,3,6,7],7]', expectedOutput: '[[2,2,3],[7]]' }],
    acceptanceRate: 46.2,
  },
  {
    slug: 'letter-combinations-phone',
    title: 'Letter Combinations of Phone Number',
    difficulty: 'medium',
    description: 'Given digits `2-9`, return all possible letter combinations (T9 keypad).',
    examples: [{ input: 'digits="23"', output: '["ad","ae","af","bd","be","bf","cd","ce","cf"]' }],
    constraints: ['0 <= digits.length <= 4', 'digits[i] in "23456789"'],
    tags: ['strings', 'recursion', 'backtracking'],
    starterCode: { 93: js('letterCombinations','digits','string[]'), 71: py('letter_combinations','digits') },
    testCases: [{ input: '"23"', expectedOutput: '["ad","ae","af","bd","be","bf","cd","ce","cf"]' }],
    acceptanceRate: 43.7,
  },
  {
    slug: 'binary-tree-level-order',
    title: 'Binary Tree Level Order Traversal',
    difficulty: 'medium',
    description: 'Return level order traversal of a binary tree (array of arrays per level).',
    examples: [{ input: 'root=[3,9,20,null,null,15,7]', output: '[[3],[9,20],[15,7]]' }],
    constraints: ['0 <= nodes <= 2000'],
    tags: ['trees', 'bfs'],
    starterCode: { 93: '// TreeNode class provided\nfunction levelOrder(root) {\n\n}', 71: 'def level_order(root):\n    pass' },
    testCases: [{ input: '[[3,9,20,null,null,15,7]]', expectedOutput: '[[3],[9,20],[15,7]]' }],
    acceptanceRate: 48.9,
  },
  {
    slug: 'validate-bst',
    title: 'Validate Binary Search Tree',
    difficulty: 'medium',
    description: 'Determine if a binary tree is a valid BST.',
    examples: [{ input: 'root=[2,1,3]', output: 'true' }, { input: 'root=[5,1,4,null,null,3,6]', output: 'false' }],
    constraints: ['-2^31 <= val <= 2^31-1'],
    tags: ['trees', 'dfs', 'recursion'],
    starterCode: { 93: '// TreeNode provided\nfunction isValidBST(root) {\n\n}', 71: 'def is_valid_bst(root):\n    pass' },
    testCases: [{ input: '[[2,1,3]]', expectedOutput: 'true' }],
    acceptanceRate: 38.4,
  },
  {
    slug: 'lowest-common-ancestor',
    title: 'Lowest Common Ancestor of BST',
    difficulty: 'medium',
    description: 'Find the LCA of nodes `p` and `q` in a BST.',
    examples: [{ input: 'root=[6,2,8,...], p=2, q=8', output: '6' }],
    constraints: ['2 <= nodes <= 10^5', 'All values unique'],
    tags: ['trees', 'recursion', 'dfs'],
    starterCode: { 93: '// TreeNode provided\nfunction lowestCommonAncestor(root, p, q) {\n\n}', 71: 'def lowest_common_ancestor(root, p, q):\n    pass' },
    testCases: [{ input: '[[6,2,8,0,4,7,9,null,null,3,5],2,8]', expectedOutput: '6' }],
    acceptanceRate: 46.1,
  },
  {
    slug: 'clone-graph',
    title: 'Clone Graph',
    difficulty: 'medium',
    description: 'Deep copy a graph where each node has a value and list of neighbors.',
    examples: [{ input: 'adjList=[[2,4],[1,3],[2,4],[1,3]]', output: 'same structure deep copied' }],
    constraints: ['0 <= nodes <= 100', 'All values unique'],
    tags: ['graphs', 'bfs', 'dfs', 'hash-map'],
    starterCode: { 93: '// Node class provided\nfunction cloneGraph(node) {\n\n}', 71: 'def clone_graph(node):\n    pass' },
    testCases: [{ input: '[[[2,4],[1,3],[2,4],[1,3]]]', expectedOutput: '[[2,4],[1,3],[2,4],[1,3]]' }],
    acceptanceRate: 37.8,
  },
  {
    slug: 'course-schedule',
    title: 'Course Schedule',
    difficulty: 'medium',
    description: 'Can you finish `numCourses` given prerequisites `[a,b]` (must take b before a)? Detect cycle.',
    examples: [{ input: 'numCourses=2, prerequisites=[[1,0]]', output: 'true' }],
    constraints: ['1 <= numCourses <= 2000', '0 <= prerequisites.length <= 5000'],
    tags: ['graphs', 'bfs', 'dfs', 'topological-sort'],
    starterCode: { 93: js('canFinish','numCourses, prerequisites','boolean'), 71: py('can_finish','numCourses, prerequisites') },
    testCases: [{ input: '[2,[[1,0]]]', expectedOutput: 'true' }, { input: '[2,[[1,0],[0,1]]]', expectedOutput: 'false' }],
    acceptanceRate: 33.9,
  },
  {
    slug: 'pacific-atlantic-flow',
    title: 'Pacific Atlantic Water Flow',
    difficulty: 'medium',
    description: 'Find cells where water can flow to both Pacific (top/left) and Atlantic (bottom/right) oceans.',
    examples: [{ input: 'heights=[[1,2,2,3,5],[3,2,3,4,4],[2,4,5,3,1],[6,7,1,4,5],[5,1,1,2,4]]', output: '[[0,4],[1,3],[1,4],[2,2],[3,0],[3,1],[4,0]]' }],
    constraints: ['1 <= m, n <= 200'],
    tags: ['graphs', 'bfs', 'dfs'],
    starterCode: { 93: js('pacificAtlantic','heights','number[][]'), 71: py('pacific_atlantic','heights') },
    testCases: [{ input: '[[[1,2,2,3,5],[3,2,3,4,4],[2,4,5,3,1],[6,7,1,4,5],[5,1,1,2,4]]]', expectedOutput: '[[0,4],[1,3],[1,4],[2,2],[3,0],[3,1],[4,0]]' }],
    acceptanceRate: 32.6,
  },
  {
    slug: 'min-stack',
    title: 'Min Stack',
    difficulty: 'medium',
    description: 'Design a stack that supports push, pop, top, and retrieving the minimum element in O(1).',
    examples: [{ input: 'push(-2), push(0), push(-3), getMin()', output: '-3' }],
    constraints: ['-2^31 <= val <= 2^31-1', 'pop/top called on non-empty stack'],
    tags: ['stack', 'oop'],
    starterCode: { 93: 'class MinStack {\n  constructor() {}\n  push(val) {}\n  pop() {}\n  top() {}\n  getMin() {}\n}', 71: 'class MinStack:\n    def __init__(self): pass\n    def push(self, val): pass\n    def pop(self): pass\n    def top(self): pass\n    def get_min(self): pass' },
    testCases: [{ input: '[["-2","0","-3"]]', expectedOutput: '-3' }],
    acceptanceRate: 45.5,
  },
  {
    slug: 'daily-temperatures',
    title: 'Daily Temperatures',
    difficulty: 'medium',
    description: 'Given temperatures, return array of days to wait for a warmer day. 0 if none.',
    examples: [{ input: 'temps=[73,74,75,71,69,72,76,73]', output: '[1,1,4,2,1,1,0,0]' }],
    constraints: ['1 <= temps.length <= 10^5', '30 <= temps[i] <= 100'],
    tags: ['arrays', 'stack'],
    starterCode: { 93: js('dailyTemperatures','temperatures','number[]'), 71: py('daily_temperatures','temperatures') },
    testCases: [{ input: '[[73,74,75,71,69,72,76,73]]', expectedOutput: '[1,1,4,2,1,1,0,0]' }],
    acceptanceRate: 47.9,
  },
  {
    slug: 'evaluate-rpn',
    title: 'Evaluate Reverse Polish Notation',
    difficulty: 'medium',
    description: 'Evaluate an expression in Reverse Polish Notation given as array of tokens.',
    examples: [{ input: 'tokens=["2","1","+","3","*"]', output: '9' }],
    constraints: ['1 <= tokens.length <= 10^4', 'Integer division truncates toward zero'],
    tags: ['stack', 'arrays'],
    starterCode: { 93: js('evalRPN','tokens','number'), 71: py('eval_rpn','tokens') },
    testCases: [{ input: '[["2","1","+","3","*"]]', expectedOutput: '9' }, { input: '[["4","13","5","/","+"]]', expectedOutput: '6' }],
    acceptanceRate: 41.2,
  },
  {
    slug: 'generate-parentheses',
    title: 'Generate Parentheses',
    difficulty: 'medium',
    description: 'Generate all combinations of well-formed parentheses for `n` pairs.',
    examples: [{ input: 'n=3', output: '["((()))","(()())","(())()","()(())","()()()"]' }],
    constraints: ['1 <= n <= 8'],
    tags: ['strings', 'recursion', 'backtracking'],
    starterCode: { 93: js('generateParenthesis','n','string[]'), 71: py('generate_parenthesis','n') },
    testCases: [{ input: '[3]', expectedOutput: '["((()))","(()())","(())()","()(())","()()()"]' }],
    acceptanceRate: 56.1,
  },
  {
    slug: 'search-rotated-array',
    title: 'Search in Rotated Sorted Array',
    difficulty: 'medium',
    description: 'Search target in a rotated sorted array. Return index or -1.',
    examples: [{ input: 'nums=[4,5,6,7,0,1,2], target=0', output: '4' }],
    constraints: ['1 <= nums.length <= 5000', 'All unique', 'O(log n) required'],
    tags: ['arrays', 'binary-search', 'searching'],
    starterCode: { 93: js('searchRotated','nums, target','number'), 71: py('search_rotated','nums, target') },
    testCases: [{ input: '[[4,5,6,7,0,1,2],0]', expectedOutput: '4' }, { input: '[[4,5,6,7,0,1,2],3]', expectedOutput: '-1' }],
    acceptanceRate: 36.7,
  },
  {
    slug: 'find-duplicate-number',
    title: 'Find the Duplicate Number',
    difficulty: 'medium',
    description: 'Find the duplicate in array of n+1 integers each in [1,n]. O(1) space, no array modification.',
    examples: [{ input: 'nums=[1,3,4,2,2]', output: '2' }],
    constraints: ['1 <= n <= 10^5', 'Only one duplicate'],
    tags: ['arrays', 'binary-search', 'two-pointers'],
    starterCode: { 93: js('findDuplicate','nums','number'), 71: py('find_duplicate','nums') },
    testCases: [{ input: '[[1,3,4,2,2]]', expectedOutput: '2' }, { input: '[[3,1,3,4,2]]', expectedOutput: '3' }],
    acceptanceRate: 34.2,
  },
  {
    slug: 'container-with-most-water',
    title: 'Container With Most Water',
    difficulty: 'medium',
    description: 'Given heights, find two lines that form a container holding the most water.',
    examples: [{ input: 'height=[1,8,6,2,5,4,8,3,7]', output: '49' }],
    constraints: ['n >= 2', '0 <= height[i] <= 10^4'],
    tags: ['arrays', 'two-pointers', 'greedy'],
    starterCode: { 93: js('maxArea','height','number'), 71: py('max_area','height') },
    testCases: [{ input: '[[1,8,6,2,5,4,8,3,7]]', expectedOutput: '49' }, { input: '[[1,1]]', expectedOutput: '1' }],
    acceptanceRate: 43.8,
  },
  {
    slug: '3sum',
    title: '3Sum',
    difficulty: 'medium',
    description: 'Find all unique triplets that sum to zero.',
    examples: [{ input: 'nums=[-1,0,1,2,-1,-4]', output: '[[-1,-1,2],[-1,0,1]]' }],
    constraints: ['0 <= nums.length <= 3000', '-10^5 <= nums[i] <= 10^5'],
    tags: ['arrays', 'two-pointers', 'sorting'],
    starterCode: { 93: js('threeSum','nums','number[][]'), 71: py('three_sum','nums') },
    testCases: [{ input: '[[-1,0,1,2,-1,-4]]', expectedOutput: '[[-1,-1,2],[-1,0,1]]' }],
    acceptanceRate: 30.4,
  },
  {
    slug: 'trapping-rain-water-medium',
    title: 'Trapping Rain Water (Prefix Max)',
    difficulty: 'medium',
    description: 'Compute water trapped after rain using prefix/suffix max arrays.',
    examples: [{ input: 'height=[0,1,0,2,1,0,1,3,2,1,2,1]', output: '6' }],
    constraints: ['0 <= height[i] <= 10^4'],
    tags: ['arrays', 'dynamic-programming', 'two-pointers'],
    starterCode: { 93: js('trap','height','number'), 71: py('trap','height') },
    testCases: [{ input: '[[0,1,0,2,1,0,1,3,2,1,2,1]]', expectedOutput: '6' }, { input: '[[4,2,0,3,2,5]]', expectedOutput: '9' }],
    acceptanceRate: 38.5,
  },
  {
    slug: 'insert-interval',
    title: 'Insert Interval',
    difficulty: 'medium',
    description: 'Insert a new interval into a sorted non-overlapping list and merge if needed.',
    examples: [{ input: 'intervals=[[1,3],[6,9]], newInterval=[2,5]', output: '[[1,5],[6,9]]' }],
    constraints: ['0 <= intervals.length <= 10^4', 'Intervals sorted by start'],
    tags: ['arrays', 'sorting'],
    starterCode: { 93: js('insert','intervals, newInterval','number[][]'), 71: py('insert','intervals, new_interval') },
    testCases: [{ input: '[[[1,3],[6,9]],[2,5]]', expectedOutput: '[[1,5],[6,9]]' }],
    acceptanceRate: 33.1,
  },
  {
    slug: 'merge-intervals',
    title: 'Merge Intervals',
    difficulty: 'medium',
    description: 'Merge all overlapping intervals and return the result.',
    examples: [{ input: 'intervals=[[1,3],[2,6],[8,10],[15,18]]', output: '[[1,6],[8,10],[15,18]]' }],
    constraints: ['1 <= intervals.length <= 10^4'],
    tags: ['arrays', 'sorting'],
    starterCode: { 93: js('merge','intervals','number[][]'), 71: py('merge','intervals') },
    testCases: [{ input: '[[[1,3],[2,6],[8,10],[15,18]]]', expectedOutput: '[[1,6],[8,10],[15,18]]' }],
    acceptanceRate: 39.2,
  },
  {
    slug: 'diameter-of-binary-tree',
    title: 'Diameter of Binary Tree',
    difficulty: 'medium',
    description: 'Find the length of the longest path between any two nodes in a tree.',
    examples: [{ input: 'root=[1,2,3,4,5]', output: '3' }],
    constraints: ['1 <= nodes <= 10^4'],
    tags: ['trees', 'dfs', 'recursion'],
    starterCode: { 93: '// TreeNode provided\nfunction diameterOfBinaryTree(root) {\n\n}', 71: 'def diameter_of_binary_tree(root):\n    pass' },
    testCases: [{ input: '[[1,2,3,4,5]]', expectedOutput: '3' }],
    acceptanceRate: 44.6,
  },
  {
    slug: 'path-sum-ii',
    title: 'Path Sum II',
    difficulty: 'medium',
    description: 'Find all root-to-leaf paths where the sum equals `targetSum`.',
    examples: [{ input: 'root=[5,4,8,11,null,13,4,7,2,null,null,5,1], targetSum=22', output: '[[5,4,11,2],[5,8,4,5]]' }],
    constraints: ['0 <= nodes <= 5000'],
    tags: ['trees', 'dfs', 'backtracking'],
    starterCode: { 93: '// TreeNode provided\nfunction pathSum(root, targetSum) {\n\n}', 71: 'def path_sum(root, target_sum):\n    pass' },
    testCases: [{ input: '[[5,4,8,11,null,13,4,7,2,null,null,5,1],22]', expectedOutput: '[[5,4,11,2],[5,8,4,5]]' }],
    acceptanceRate: 42.3,
  },
  {
    slug: 'construct-bst-preorder',
    title: 'Construct BST from Preorder',
    difficulty: 'medium',
    description: 'Reconstruct a BST from its preorder traversal.',
    examples: [{ input: 'preorder=[8,5,1,7,10,12]', output: '[8,5,10,1,7,null,12]' }],
    constraints: ['1 <= preorder.length <= 100', 'All values unique'],
    tags: ['trees', 'recursion'],
    starterCode: { 93: '// TreeNode provided\nfunction bstFromPreorder(preorder) {\n\n}', 71: 'def bst_from_preorder(preorder):\n    pass' },
    testCases: [{ input: '[[8,5,1,7,10,12]]', expectedOutput: '[8,5,10,1,7,null,12]' }],
    acceptanceRate: 55.7,
  },
  {
    slug: 'task-scheduler',
    title: 'Task Scheduler',
    difficulty: 'medium',
    description: 'Given CPU tasks and cooldown `n`, find minimum intervals to finish all tasks.',
    examples: [{ input: 'tasks=["A","A","A","B","B","B"], n=2', output: '8' }],
    constraints: ['1 <= tasks.length <= 10^4', '0 <= n <= 100'],
    tags: ['arrays', 'heap', 'greedy'],
    starterCode: { 93: js('leastInterval','tasks, n','number'), 71: py('least_interval','tasks, n') },
    testCases: [{ input: '[["A","A","A","B","B","B"],2]', expectedOutput: '8' }],
    acceptanceRate: 39.8,
  },
  {
    slug: 'gas-station',
    title: 'Gas Station',
    difficulty: 'medium',
    description: 'Find the starting gas station index to complete a circular route. Return -1 if impossible.',
    examples: [{ input: 'gas=[1,2,3,4,5], cost=[3,4,5,1,2]', output: '3' }],
    constraints: ['n == gas.length == cost.length', '1 <= n <= 10^5'],
    tags: ['arrays', 'greedy'],
    starterCode: { 93: js('canCompleteCircuit','gas, cost','number'), 71: py('can_complete_circuit','gas, cost') },
    testCases: [{ input: '[[1,2,3,4,5],[3,4,5,1,2]]', expectedOutput: '3' }, { input: '[[2,3,4],[3,4,3]]', expectedOutput: '-1' }],
    acceptanceRate: 37.4,
  },
  {
    slug: 'partition-equal-subset',
    title: 'Partition Equal Subset Sum',
    difficulty: 'medium',
    description: 'Can `nums` be partitioned into two subsets with equal sums?',
    examples: [{ input: 'nums=[1,5,11,5]', output: 'true' }],
    constraints: ['1 <= nums.length <= 200', '1 <= nums[i] <= 100'],
    tags: ['dynamic-programming', 'arrays'],
    starterCode: { 93: js('canPartition','nums','boolean'), 71: py('can_partition','nums') },
    testCases: [{ input: '[[1,5,11,5]]', expectedOutput: 'true' }, { input: '[[1,2,3,5]]', expectedOutput: 'false' }],
    acceptanceRate: 36.8,
  },
  {
    slug: 'longest-palindromic-substring',
    title: 'Longest Palindromic Substring',
    difficulty: 'medium',
    description: 'Find the longest palindromic substring in `s`.',
    examples: [{ input: 's="babad"', output: '"bab"' }],
    constraints: ['1 <= s.length <= 1000', 's has lowercase English and digits'],
    tags: ['strings', 'dynamic-programming'],
    starterCode: { 93: js('longestPalindrome','s','string'), 71: py('longest_palindrome','s') },
    testCases: [{ input: '"babad"', expectedOutput: '"bab"' }, { input: '"cbbd"', expectedOutput: '"bb"' }],
    acceptanceRate: 31.7,
  },
  {
    slug: 'decode-ways',
    title: 'Decode Ways',
    difficulty: 'medium',
    description: 'Count ways to decode a digit string where A=1, B=2,..., Z=26.',
    examples: [{ input: 's="226"', output: '3' }],
    constraints: ['1 <= s.length <= 100', 's contains only digits'],
    tags: ['strings', 'dynamic-programming'],
    starterCode: { 93: js('numDecodings','s','number'), 71: py('num_decodings','s') },
    testCases: [{ input: '"226"', expectedOutput: '3' }, { input: '"06"', expectedOutput: '0' }],
    acceptanceRate: 27.5,
  },
  {
    slug: 'word-break',
    title: 'Word Break',
    difficulty: 'medium',
    description: 'Can string `s` be segmented into words from `wordDict`?',
    examples: [{ input: 's="leetcode", wordDict=["leet","code"]', output: 'true' }],
    constraints: ['1 <= s.length <= 300', '1 <= wordDict.length <= 1000'],
    tags: ['strings', 'dynamic-programming', 'hash-map'],
    starterCode: { 93: js('wordBreak','s, wordDict','boolean'), 71: py('word_break','s, word_dict') },
    testCases: [{ input: '["leetcode",["leet","code"]]', expectedOutput: 'true' }, { input: '["applepenapple",["apple","pen"]]', expectedOutput: 'true' }],
    acceptanceRate: 38.9,
  },

  // ── HARD (30) ─────────────────────────────────────────────────────────────
  {
    slug: 'median-two-sorted-arrays',
    title: 'Median of Two Sorted Arrays',
    difficulty: 'hard',
    description: 'Find the median of two sorted arrays in O(log(m+n)) time.',
    examples: [{ input: 'nums1=[1,3], nums2=[2]', output: '2.0' }],
    constraints: ['0 <= m, n <= 1000', 'm + n >= 1'],
    tags: ['arrays', 'binary-search', 'searching'],
    starterCode: { 93: js('findMedianSortedArrays','nums1, nums2','number'), 71: py('find_median_sorted_arrays','nums1, nums2') },
    testCases: [{ input: '[[1,3],[2]]', expectedOutput: '2.0' }, { input: '[[1,2],[3,4]]', expectedOutput: '2.5' }],
    acceptanceRate: 28.1,
  },
  {
    slug: 'trapping-rain-water',
    title: 'Trapping Rain Water',
    difficulty: 'hard',
    description: 'Compute water trapped after rain using two-pointer approach in O(n) time and O(1) space.',
    examples: [{ input: 'height=[0,1,0,2,1,0,1,3,2,1,2,1]', output: '6' }],
    constraints: ['0 <= height[i] <= 10^4'],
    tags: ['arrays', 'two-pointers', 'dynamic-programming'],
    starterCode: { 93: js('trap','height','number'), 71: py('trap','height') },
    testCases: [{ input: '[[0,1,0,2,1,0,1,3,2,1,2,1]]', expectedOutput: '6' }, { input: '[[4,2,0,3,2,5]]', expectedOutput: '9' }],
    acceptanceRate: 33.8,
  },
  {
    slug: 'n-queens',
    title: 'N-Queens',
    difficulty: 'hard',
    description: 'Place N queens on an N×N board so no two attack each other. Return all distinct solutions.',
    examples: [{ input: 'n=4', output: '[[".Q..","...Q","Q...","..Q."],["..Q.","Q...","...Q",".Q.."]]' }],
    constraints: ['1 <= n <= 9'],
    tags: ['recursion', 'backtracking'],
    starterCode: { 93: js('solveNQueens','n','string[][]'), 71: py('solve_n_queens','n') },
    testCases: [{ input: '[4]', expectedOutput: '[[".Q..","...Q","Q...","..Q."],["..Q.","Q...","...Q",".Q.."]]' }],
    acceptanceRate: 22.4,
  },
  {
    slug: 'sudoku-solver',
    title: 'Sudoku Solver',
    difficulty: 'hard',
    description: 'Solve a Sudoku puzzle in-place.',
    examples: [{ input: '9x9 board with some filled', output: 'completed board' }],
    constraints: ['Input has exactly one solution'],
    tags: ['arrays', 'recursion', 'backtracking'],
    starterCode: { 93: js('solveSudoku','board','void'), 71: py('solve_sudoku','board') },
    testCases: [{ input: '[["5","3",".",".","7",".",".",".","."],["6",".",".","1","9","5",".",".","."],[".","9","8",".",".",".",".","6","."],["8",".",".",".","6",".",".",".","3"],["4",".",".","8",".","3",".",".","1"],["7",".",".",".","2",".",".",".","6"],[".","6",".",".",".",".","2","8","."],[".",".",".","4","1","9",".",".","5"],[".",".",".",".","8",".",".","7","9"]]', expectedOutput: '[["5","3","4","6","7","8","9","1","2"],["6","7","2","1","9","5","3","4","8"],["1","9","8","3","4","2","5","6","7"],["8","5","9","7","6","1","4","2","3"],["4","2","6","8","5","3","7","9","1"],["7","1","3","9","2","4","8","5","6"],["9","6","1","5","3","7","2","8","4"],["2","8","7","4","1","9","6","3","5"],["3","4","5","2","8","6","1","7","9"]]' }],
    acceptanceRate: 17.8,
  },
  {
    slug: 'largest-rectangle-histogram',
    title: 'Largest Rectangle in Histogram',
    difficulty: 'hard',
    description: 'Find the largest rectangle area in a histogram.',
    examples: [{ input: 'heights=[2,1,5,6,2,3]', output: '10' }],
    constraints: ['1 <= heights.length <= 10^5', '0 <= heights[i] <= 10^4'],
    tags: ['arrays', 'stack'],
    starterCode: { 93: js('largestRectangleArea','heights','number'), 71: py('largest_rectangle_area','heights') },
    testCases: [{ input: '[[2,1,5,6,2,3]]', expectedOutput: '10' }, { input: '[[2,4]]', expectedOutput: '4' }],
    acceptanceRate: 25.3,
  },
  {
    slug: 'word-ladder',
    title: 'Word Ladder',
    difficulty: 'hard',
    description: 'Shortest transformation sequence from `beginWord` to `endWord`, changing one letter at a time.',
    examples: [{ input: 'begin="hit", end="cog", wordList=["hot","dot","dog","lot","log","cog"]', output: '5' }],
    constraints: ['1 <= beginWord.length <= 10', 'All words same length'],
    tags: ['graphs', 'bfs', 'hash-map'],
    starterCode: { 93: js('ladderLength','beginWord, endWord, wordList','number'), 71: py('ladder_length','begin_word, end_word, word_list') },
    testCases: [{ input: '["hit","cog",["hot","dot","dog","lot","log","cog"]]', expectedOutput: '5' }],
    acceptanceRate: 24.7,
  },
  {
    slug: 'serialize-deserialize-tree',
    title: 'Serialize and Deserialize Binary Tree',
    difficulty: 'hard',
    description: 'Design an algorithm to serialize a binary tree to string and deserialize it back.',
    examples: [{ input: 'root=[1,2,3,null,null,4,5]', output: 'same tree after round-trip' }],
    constraints: ['0 <= nodes <= 10^4', '-1000 <= val <= 1000'],
    tags: ['trees', 'bfs', 'dfs', 'serialization'],
    starterCode: { 93: '// TreeNode provided\nfunction serialize(root) {}\nfunction deserialize(data) {}', 71: 'def serialize(root): pass\ndef deserialize(data): pass' },
    testCases: [{ input: '[[1,2,3,null,null,4,5]]', expectedOutput: '[1,2,3,null,null,4,5]' }],
    acceptanceRate: 29.4,
  },
  {
    slug: 'alien-dictionary',
    title: 'Alien Dictionary',
    difficulty: 'hard',
    description: 'Given sorted words in alien language, determine the order of letters. Return empty string if invalid.',
    examples: [{ input: 'words=["wrt","wrf","er","ett","rftt"]', output: '"wertf"' }],
    constraints: ['1 <= words.length <= 100', '1 <= words[i].length <= 100'],
    tags: ['graphs', 'topological-sort', 'dfs', 'bfs'],
    starterCode: { 93: js('alienOrder','words','string'), 71: py('alien_order','words') },
    testCases: [{ input: '[["wrt","wrf","er","ett","rftt"]]', expectedOutput: '"wertf"' }],
    acceptanceRate: 21.9,
  },
  {
    slug: 'minimum-window-substring',
    title: 'Minimum Window Substring',
    difficulty: 'hard',
    description: 'Find minimum window in `s` that contains all characters of `t`. Return "" if none.',
    examples: [{ input: 's="ADOBECODEBANC", t="ABC"', output: '"BANC"' }],
    constraints: ['1 <= s.length <= 10^5', '1 <= t.length <= 10^5'],
    tags: ['strings', 'hash-map', 'sliding-window'],
    starterCode: { 93: js('minWindow','s, t','string'), 71: py('min_window','s, t') },
    testCases: [{ input: '["ADOBECODEBANC","ABC"]', expectedOutput: '"BANC"' }, { input: '["a","aa"]', expectedOutput: '""' }],
    acceptanceRate: 24.5,
  },
  {
    slug: 'sliding-window-maximum',
    title: 'Sliding Window Maximum',
    difficulty: 'hard',
    description: 'Return max values in every sliding window of size `k` over `nums`.',
    examples: [{ input: 'nums=[1,3,-1,-3,5,3,6,7], k=3', output: '[3,3,5,5,6,7]' }],
    constraints: ['1 <= k <= nums.length <= 10^5'],
    tags: ['arrays', 'queue', 'sliding-window'],
    starterCode: { 93: js('maxSlidingWindow','nums, k','number[]'), 71: py('max_sliding_window','nums, k') },
    testCases: [{ input: '[[1,3,-1,-3,5,3,6,7],3]', expectedOutput: '[3,3,5,5,6,7]' }],
    acceptanceRate: 26.8,
  },
  {
    slug: 'longest-increasing-subsequence',
    title: 'Longest Increasing Subsequence',
    difficulty: 'hard',
    description: 'Find the length of the longest strictly increasing subsequence.',
    examples: [{ input: 'nums=[10,9,2,5,3,7,101,18]', output: '4' }],
    constraints: ['1 <= nums.length <= 2500'],
    tags: ['dynamic-programming', 'binary-search'],
    starterCode: { 93: js('lengthOfLIS','nums','number'), 71: py('length_of_lis','nums') },
    testCases: [{ input: '[[10,9,2,5,3,7,101,18]]', expectedOutput: '4' }, { input: '[[0,1,0,3,2,3]]', expectedOutput: '4' }],
    acceptanceRate: 31.6,
  },
  {
    slug: 'edit-distance',
    title: 'Edit Distance (Levenshtein)',
    difficulty: 'hard',
    description: 'Find minimum operations (insert, delete, replace) to convert `word1` to `word2`.',
    examples: [{ input: 'word1="horse", word2="ros"', output: '3' }],
    constraints: ['0 <= word1.length, word2.length <= 500'],
    tags: ['strings', 'dynamic-programming'],
    starterCode: { 93: js('minDistance','word1, word2','number'), 71: py('min_distance','word1, word2') },
    testCases: [{ input: '["horse","ros"]', expectedOutput: '3' }, { input: '["intention","execution"]', expectedOutput: '5' }],
    acceptanceRate: 23.7,
  },
  {
    slug: 'regular-expression-matching',
    title: 'Regular Expression Matching',
    difficulty: 'hard',
    description: 'Implement regex matching with `.` and `*`.',
    examples: [{ input: 's="aa", p="a*"', output: 'true' }],
    constraints: ['1 <= s.length <= 20', '1 <= p.length <= 30'],
    tags: ['strings', 'dynamic-programming', 'recursion'],
    starterCode: { 93: js('isMatch','s, p','boolean'), 71: py('is_match','s, p') },
    testCases: [{ input: '["aa","a*"]', expectedOutput: 'true' }, { input: '["aab","c*a*b"]', expectedOutput: 'true' }],
    acceptanceRate: 18.9,
  },
  {
    slug: 'burst-balloons',
    title: 'Burst Balloons',
    difficulty: 'hard',
    description: 'Burst all balloons to maximize coins. Coins = nums[left]*nums[i]*nums[right].',
    examples: [{ input: 'nums=[3,1,5,8]', output: '167' }],
    constraints: ['1 <= nums.length <= 300', '0 <= nums[i] <= 100'],
    tags: ['dynamic-programming', 'recursion'],
    starterCode: { 93: js('maxCoins','nums','number'), 71: py('max_coins','nums') },
    testCases: [{ input: '[[3,1,5,8]]', expectedOutput: '167' }, { input: '[[1,5]]', expectedOutput: '10' }],
    acceptanceRate: 19.4,
  },
  {
    slug: 'count-smaller-after-self',
    title: 'Count of Smaller Numbers After Self',
    difficulty: 'hard',
    description: 'For each element, count how many smaller elements appear to its right.',
    examples: [{ input: 'nums=[5,2,6,1]', output: '[2,1,1,0]' }],
    constraints: ['1 <= nums.length <= 10^5', '-10^4 <= nums[i] <= 10^4'],
    tags: ['arrays', 'sorting', 'searching'],
    starterCode: { 93: js('countSmaller','nums','number[]'), 71: py('count_smaller','nums') },
    testCases: [{ input: '[[5,2,6,1]]', expectedOutput: '[2,1,1,0]' }],
    acceptanceRate: 22.1,
  },
  {
    slug: 'maximal-rectangle',
    title: 'Maximal Rectangle',
    difficulty: 'hard',
    description: 'Find the largest rectangle containing only 1s in a binary matrix.',
    examples: [{ input: 'matrix=[["1","0","1","0"],["1","0","1","1"],["1","1","1","1"],["1","0","0","1"]]', output: '6' }],
    constraints: ['0 <= m, n <= 200'],
    tags: ['arrays', 'stack', 'dynamic-programming'],
    starterCode: { 93: js('maximalRectangle','matrix','number'), 71: py('maximal_rectangle','matrix') },
    testCases: [{ input: '[[["1","0","1","0","0"],["1","0","1","1","1"],["1","1","1","1","1"],["1","0","0","1","0"]]]', expectedOutput: '6' }],
    acceptanceRate: 20.3,
  },
  {
    slug: 'avl-tree-insert',
    title: 'AVL Tree Insert',
    difficulty: 'hard',
    description: 'Implement AVL tree insertion with rotations. Return the in-order traversal of the balanced tree.',
    examples: [{ input: 'keys=[10,20,30,40,50,25]', output: '[10,20,25,30,40,50]' }],
    constraints: ['1 <= keys.length <= 100', 'All keys distinct'],
    tags: ['trees', 'avl-trees'],
    starterCode: { 93: '// Implement AVLNode and insert\nfunction avlInOrder(keys) {\n\n}', 71: 'def avl_in_order(keys):\n    pass' },
    testCases: [{ input: '[[10,20,30,40,50,25]]', expectedOutput: '[10,20,25,30,40,50]' }],
    acceptanceRate: 16.7,
  },
  {
    slug: 'concurrent-bank-transfer',
    title: 'Concurrent Bank Transfers',
    difficulty: 'hard',
    description: 'Implement a thread-safe bank account class supporting concurrent deposits and withdrawals without deadlock.',
    examples: [{ input: 'deposit(100), withdraw(50), balance()', output: '50' }],
    constraints: ['Multiple threads may call simultaneously'],
    tags: ['concurrency', 'synchronization', 'threads'],
    starterCode: { 93: '// Implement thread-safe BankAccount\nclass BankAccount {\n  constructor(balance) {}\n  deposit(amount) {}\n  withdraw(amount) {}\n  getBalance() {}\n}', 71: 'import threading\nclass BankAccount:\n    def __init__(self, balance): pass\n    def deposit(self, amount): pass\n    def withdraw(self, amount): pass\n    def get_balance(self): pass' },
    testCases: [{ input: '[100,50]', expectedOutput: '50' }],
    acceptanceRate: 14.2,
  },
  {
    slug: 'find-median-data-stream',
    title: 'Find Median from Data Stream',
    difficulty: 'hard',
    description: 'Design a data structure to find the median from a stream of numbers in O(log n) per operation.',
    examples: [{ input: 'add(1), add(2), findMedian(), add(3), findMedian()', output: '1.5, 2.0' }],
    constraints: ['-10^5 <= num <= 10^5', 'At least one element before findMedian'],
    tags: ['heap', 'sorting'],
    starterCode: { 93: 'class MedianFinder {\n  constructor() {}\n  addNum(num) {}\n  findMedian() {}\n}', 71: 'class MedianFinder:\n    def __init__(self): pass\n    def add_num(self, num): pass\n    def find_median(self): pass' },
    testCases: [{ input: '[[1,2,3]]', expectedOutput: '[1.5,2.0]' }],
    acceptanceRate: 21.8,
  },
  {
    slug: 'skyline-problem',
    title: 'Skyline Problem',
    difficulty: 'hard',
    description: 'Find the skyline formed by buildings. Return critical points where height changes.',
    examples: [{ input: 'buildings=[[2,9,10],[3,7,15],[5,12,12]]', output: '[[2,10],[3,15],[7,12],[12,0]]' }],
    constraints: ['0 <= buildings.length <= 10^4'],
    tags: ['heap', 'sorting', 'divide-and-conquer'],
    starterCode: { 93: js('getSkyline','buildings','number[][]'), 71: py('get_skyline','buildings') },
    testCases: [{ input: '[[[2,9,10],[3,7,15],[5,12,12],[15,20,10],[19,24,8]]]', expectedOutput: '[[2,10],[3,15],[7,12],[12,0],[15,10],[20,8],[24,0]]' }],
    acceptanceRate: 17.3,
  },
  {
    slug: 'max-points-on-line',
    title: 'Max Points on a Line',
    difficulty: 'hard',
    description: 'Find the maximum number of points that lie on the same straight line.',
    examples: [{ input: 'points=[[1,1],[2,2],[3,3]]', output: '3' }],
    constraints: ['1 <= points.length <= 300'],
    tags: ['arrays', 'hash-map', 'math'],
    starterCode: { 93: js('maxPoints','points','number'), 71: py('max_points','points') },
    testCases: [{ input: '[[[1,1],[2,2],[3,3]]]', expectedOutput: '3' }, { input: '[[[1,1],[3,2],[5,3],[4,1],[2,3],[1,4]]]', expectedOutput: '4' }],
    acceptanceRate: 18.6,
  },
  {
    slug: 'remove-invalid-parentheses',
    title: 'Remove Invalid Parentheses',
    difficulty: 'hard',
    description: 'Remove minimum invalid parentheses to make it valid. Return all unique results.',
    examples: [{ input: 's="()())()"', output: '["(())()","()()()"]' }],
    constraints: ['1 <= s.length <= 25'],
    tags: ['strings', 'bfs', 'recursion', 'backtracking'],
    starterCode: { 93: js('removeInvalidParentheses','s','string[]'), 71: py('remove_invalid_parentheses','s') },
    testCases: [{ input: '"()())()"', expectedOutput: '["(())()","()()()"]' }],
    acceptanceRate: 19.7,
  },
  {
    slug: 'cut-off-trees',
    title: 'Cut Off Trees for Golf Event',
    difficulty: 'hard',
    description: 'Cut trees in order of height using BFS, returning total steps. Return -1 if impossible.',
    examples: [{ input: 'forest=[[1,2,3],[0,0,4],[7,6,5]]', output: '6' }],
    constraints: ['1 <= m, n <= 50', '0 <= forest[i][j] <= 10^9'],
    tags: ['graphs', 'bfs'],
    starterCode: { 93: js('cutOffTree','forest','number'), 71: py('cut_off_tree','forest') },
    testCases: [{ input: '[[[1,2,3],[0,0,4],[7,6,5]]]', expectedOutput: '6' }],
    acceptanceRate: 15.8,
  },
  {
    slug: 'robot-room-cleaner',
    title: 'Robot Room Cleaner',
    difficulty: 'hard',
    description: 'Given a robot API (move, turnLeft, turnRight, clean), clean all accessible cells. API-only problem.',
    examples: [{ input: 'room has obstacles', output: 'all accessible cells cleaned' }],
    constraints: ['Use only robot API', 'No direct room access'],
    tags: ['graphs', 'dfs', 'recursion'],
    starterCode: { 93: '// Robot API: move(), turnLeft(), turnRight(), clean()\nfunction cleanRoom(robot) {\n\n}', 71: 'def clean_room(robot):\n    pass' },
    testCases: [{ input: '[[[1,1,1,1,1,0,1,1],[1,1,1,1,1,0,1,1],[1,1,1,1,1,1,1,1],[0,0,0,1,0,0,0,0],[1,1,1,1,1,1,1,1]],1,3]', expectedOutput: 'true' }],
    acceptanceRate: 13.9,
  },
  {
    slug: 'smallest-range-k-lists',
    title: 'Smallest Range Covering K Lists',
    difficulty: 'hard',
    description: 'Find the smallest range that includes at least one element from each of k sorted lists.',
    examples: [{ input: 'nums=[[4,10,15,24,26],[0,9,12,20],[5,18,22,30]]', output: '[20,24]' }],
    constraints: ['1 <= nums.length <= 3500', '1 <= nums[i].length <= 50'],
    tags: ['arrays', 'heap', 'sliding-window'],
    starterCode: { 93: js('smallestRange','nums','number[]'), 71: py('smallest_range','nums') },
    testCases: [{ input: '[[[4,10,15,24,26],[0,9,12,20],[5,18,22,30]]]', expectedOutput: '[20,24]' }],
    acceptanceRate: 16.4,
  },
  {
    slug: 'binary-tree-max-path-sum',
    title: 'Binary Tree Maximum Path Sum',
    difficulty: 'hard',
    description: 'Find the maximum path sum in a binary tree. Path can start and end at any node.',
    examples: [{ input: 'root=[-10,9,20,null,null,15,7]', output: '42' }],
    constraints: ['-1000 <= val <= 1000', '1 <= nodes <= 3*10^4'],
    tags: ['trees', 'dfs', 'dynamic-programming'],
    starterCode: { 93: '// TreeNode provided\nfunction maxPathSum(root) {\n\n}', 71: 'def max_path_sum(root):\n    pass' },
    testCases: [{ input: '[[-10,9,20,null,null,15,7]]', expectedOutput: '42' }],
    acceptanceRate: 26.9,
  },
  {
    slug: 'reverse-nodes-k-group',
    title: 'Reverse Nodes in k-Group',
    difficulty: 'hard',
    description: 'Reverse linked list nodes in groups of k. Leave remaining nodes as-is.',
    examples: [{ input: 'head=[1,2,3,4,5], k=2', output: '[2,1,4,3,5]' }],
    constraints: ['1 <= k <= n', 'Use O(1) extra space'],
    tags: ['linked-list', 'recursion'],
    starterCode: { 93: '// ListNode provided\nfunction reverseKGroup(head, k) {\n\n}', 71: 'def reverse_k_group(head, k):\n    pass' },
    testCases: [{ input: '[[1,2,3,4,5],2]', expectedOutput: '[2,1,4,3,5]' }, { input: '[[1,2,3,4,5],3]', expectedOutput: '[3,2,1,4,5]' }],
    acceptanceRate: 25.4,
  },
  {
    slug: 'merge-k-sorted-lists',
    title: 'Merge K Sorted Lists',
    difficulty: 'hard',
    description: 'Merge k sorted linked lists into one sorted list.',
    examples: [{ input: 'lists=[[1,4,5],[1,3,4],[2,6]]', output: '[1,1,2,3,4,4,5,6]' }],
    constraints: ['0 <= lists.length <= 10^4', 'Each list is sorted'],
    tags: ['linked-list', 'heap', 'divide-and-conquer'],
    starterCode: { 93: '// ListNode provided\nfunction mergeKLists(lists) {\n\n}', 71: 'def merge_k_lists(lists):\n    pass' },
    testCases: [{ input: '[[[1,4,5],[1,3,4],[2,6]]]', expectedOutput: '[1,1,2,3,4,4,5,6]' }],
    acceptanceRate: 27.2,
  },
];

async function seed100(): Promise<void> {
  console.log('Seeding 100 problems...');

  for (const problem of problems) {
    await pool.query(
      `INSERT INTO problems (slug, title, difficulty, description, examples, constraints, starter_code, test_cases, tags, acceptance_rate)
       VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
       ON CONFLICT (slug) DO UPDATE SET
         title = EXCLUDED.title,
         difficulty = EXCLUDED.difficulty,
         description = EXCLUDED.description,
         examples = EXCLUDED.examples,
         constraints = EXCLUDED.constraints,
         starter_code = EXCLUDED.starter_code,
         test_cases = EXCLUDED.test_cases,
         tags = EXCLUDED.tags,
         acceptance_rate = EXCLUDED.acceptance_rate`,
      [
        problem.slug,
        problem.title,
        problem.difficulty,
        problem.description,
        JSON.stringify(problem.examples),
        JSON.stringify(problem.constraints),
        JSON.stringify(problem.starterCode),
        JSON.stringify(problem.testCases),
        problem.tags,
        problem.acceptanceRate,
      ]
    );
    console.log(`  ✓ [${problem.difficulty}] ${problem.title}`);
  }

  console.log(`\nSeeded ${problems.length} problems total.`);
  await pool.end();
}

seed100().catch((err) => {
  console.error(err);
  process.exit(1);
});
